#!/usr/bin/env python2
from importlib import import_module
from sys import exit

from tqdm import trange

decrypt_rail = import_module("34-rail-fence").decrypt
decrypt_vigenere = import_module("33-vigenere").decrypt_vigenere


ciphertext = "MSSHR SXHHK XETLN XITKH EVMSA RWEWS GRRTR DBMTL TIHGA KSFMQ UUCOG HIXIH XRCBV YGEDX PLHFZ HIHQG JHLTL RIWYE WRZGS RKUKH RKUVX DFVUK RKJVD UFGUR DKFWR UDUIL YURTV DPEJE EKIUJ VUGFL GCYWV VRBFK JRHSJ PRCOW EWZLO EIGDO FRVHN ILXVW NKDDI YMBVI SLPXR JUAXZ WSAEG XEKDA LFMEU THLRX EAGTR VSEPP ICHYP EVPDN AKZXA SWTEX ATXAQ EGAXB SIANH GXWTN HMELD THMIH IMXLI WEEHP LQTUH KMSCN EFVWE RUEIW HDLVC BKVYR TZIFU HIREK BSXUN TXDYY ICWWF FRKVG XJIUS VYRJU DDCYC VRBFV VJHWV ITXRP FYKGZ FDUCJ ZQLGV YHRRJ CNWEC WEIHU VIRKQ IKIRZ HHFKV TULFZ RSUHR RWUHG EMMNY ROPTM INERT CMXAQ GSSDO TPAIE ACMRT ADFTP IIEEH SEIWH EEILR WBRLM LIKEV XNSGA RVSEB WPXOG HLPTU JLEPT REEFS FTWKH SAEST HWGHE VALNF XVTGX ORXLI ESMTJ JREFI MKJKX KTNHK GDFRK KZEZJ SYIYR VDUVE LUHKC DJKDZ VVNLQ BJVDK RWFZC LVLJU DUGLY VIPKD SCVPH SKIBJ QDZVZ RKUFR SVRWV GIEHH XKEVV HCXVF DHJKK NOURJ RJTIA TUIXR STHVR QLSPF KVIWN XXWTE UPOQR EYTMM VFATM VQYRF TJWRW ATEWD IHXJW EATXE XRIAK PEBRY LXSSS MXIID TOSLI FTGXL ADMLT YVHCH WLWDO GFXRB TBXHH GDXFO TQRZJ FUHZF VRRRV LHRVU IJJKT HVEQR VDUKD JKUEF LJYRR UIRJH YVHIZ UKVOK MIVYQ YEKZV OKZGK VLTKQ WFKVV QJFHF VHIEK ZKVJV DZXWJ JOKKV LRXZV WUKEJ IQIEL IFFOO LXYXT TGLYV NRPEH QTANW YWENG BMLRC LKXIH ULXRI EFMHY WHRXA ESDIO LIHEI LMHET DFAPJ AIPAK MHAIL IQPKL HHKAH YBIQW DABNH IRARI HHTFF WXNHM TIMIA XBIHN EPYKM PWKUX KSDDW FSRGR CJZGD RUVKK VBVER CJHRB KEKUP KSDHH RVEIQ ZDJZK QQFKE UKIEV VRRJM RKYVH ZVJYR LIFKY QWKLU IXHZV IVQUF VKRHH IVVRQ WXYYW YQJJU JNGEF BRPLU MKTBL HPMUX LEXEH EAFJH DPNDU AYYTA CMAMX TSKEH XHHVN MBOEW SELAS VHMKS VTTVB SIBSX MUIET ETCRT FWXIX WRRFL IWMXL IPYFW KRFTT ZGIEB IXHRK XSRBN WXZJD RTFJF RHKTP OOXZC YZHPV VXFUX GPLJD TJZYV BSJYJ IUOUK SJWPE YJRHU KVTIH VFRVX RRIJJ MLDCD DCHZI UXUWU IGYVF DFCEE XGKUF KHLCU CVKDU REDVH IVREH DEZRI GVMSA ZIAGT AXLIH BDIBE HEROT KIAIG XWXAT KTLES SZMYS OAMXE IOGYT WVPHM EMCEV MXRXF AXAIR EYAIM VTDEP PLEOI XVPAU BMIWN IXGYP MYGHL EHSYW VADEA ESWLW IGERH XFQEI HFVQM ZWYIH DJKWY VFLKR WWLVD YKJIU WNEVL MOWPQ JYWIF KFJXM VHJFH JMHRJ LYVQE VPJIO KVUJT OLROV UQVVH FPQPY KKRFI JEKXK LFUKU KKKHR LDKJW KVKUU ETHAM JMOHI FGMSE TXJYS SHMOQ ZOERA HNEXT SESTT BLSSF KEHYI SXKIH FOTAC ECHXE SRINB UHIFI MXMMR BUXCS SIVGP XNTTG XPETU EEIUN AGILD EIEIW RHLMR SOWAA MRPRL GKPZK EKPFV WVDMY VULUI KZWHW CDFGV JPZKF WRJPV UEJFX GMQLU XILXI EJGWN KKVWY QIEPT VRKFY XZRVL GSZLY RLPVW EBJVW IPVCZ GFFVZ IDWYF LDRBC KZUPW FVKKD HZSBF EZTPG AWMCS HEHTE HMWEK OAYYX GIEKA CBRME QHAHY LUYHN HCHRU APNTR KRGYT WYXGH KEKOV MRXAS VARWX TXVRI PRVXA IWHPE HEKIL BRAIT LMSSH MMEHX UEEEM RXEEX ETRZL VVZQH FVYJH HISVR DKKER FLRKR ZLUOE ZCCXD RKKVW UNZYJ HLRDC KVHRV RFOPT IVDRO FCKJH UKDRK JRCZN VUKYV RVQGK XFEDE JJRJH RLRIR HZMCE RHWVY CELRG LIYHS VDRFF IHTDY XWQCI HLRVT CWLRX NSLWR IETXE EMEDX PPMED WXVVW DLHTL EIAKP IEHXX CJTWV AVJEE HGPXR IWBLM SEMGL HIHBP SZAHG GECRL XHHAH ETZLZ AHMDM VSAEE XWZNI HFKSG JRWIL SRQKR GUFRC KUNJK NKHCM RYKFK IJEZK EYHVI DURJR WDRSV UVXUY DKRON RGUVL FYGFU OYGHV KWRVQ WTVSJ HIVVV KHFFF VXVSS HYTGE NWVPL UZJII OSJQT TWYTI EKKIL YOTSH HXOXS TXVEK IRWIF MTRAI FKVAX ZHZEE XFRTG CLIBB SIKRN HIO".replace(" ", "")

# brute-force: rail-fence then vigenere, run with pypy
for i in trange(2, 100):
    c2 = decrypt_rail(ciphertext, i)
    for t in range(1, 50):
        m, vig_key = decrypt_vigenere(c2, t)
        if m.startswith("THIS"):
            print(i, t, m, vig_key)
            exit()
